package adapter

import (
	"context"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/itaywol/adeptability/pkg/adept"
)

// loadFixtureAdapter loads testdata/<dir>/adapter.yaml through the validator
// + loader pipeline so tests exercise the same path production code uses.
func loadFixtureAdapter(t *testing.T, dir string) adept.HarnessAdapter {
	t.Helper()
	v, err := NewSchemaValidator()
	require.NoError(t, err)
	loader := NewLoader(v, nil, nil)
	a, err := loader.LoadFile(filepath.Join("testdata", dir, "adapter.yaml"))
	require.NoError(t, err)
	return a
}

// writeFile is a tiny helper that creates parent dirs and writes content.
func writeFile(t *testing.T, path, content string) {
	t.Helper()
	require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
}

// TestImport_PerSkill_ReversesRenameAndBodyWrappers verifies the full per-skill
// reverse pipeline against the Junie-style fixture: rename inverted, prefix +
// suffix stripped, default activation applied, replace-rule warning emitted.
func TestImport_PerSkill_ReversesRenameAndBodyWrappers(t *testing.T) {
	a := loadFixtureAdapter(t, "import-per-skill")
	root := t.TempDir()
	writeFile(t, filepath.Join(root, ".junie", "guidelines", "alpha.md"),
		"---\ndesc: alpha description\ntags:\n  - first\n  - second\n---\n"+
			"> Auto-generated by adeptability. Do not edit by hand.\n\n"+
			"body content here\n"+
			"\n<!-- end -->")
	writeFile(t, filepath.Join(root, ".junie", "guidelines", "beta.md"),
		"---\ndesc: beta description\n---\n"+
			"> Auto-generated by adeptability. Do not edit by hand.\n\n"+
			"beta body\n"+
			"\n<!-- end -->")

	out, err := a.Import(context.Background(), root)
	require.NoError(t, err)
	require.Len(t, out, 2)

	require.Equal(t, "alpha", out[0].Skill.ID)
	require.Equal(t, "alpha description", out[0].Skill.Description)
	require.Equal(t, []string{"first", "second"}, out[0].Skill.Tags)
	require.Equal(t, adept.ActivationAgent, out[0].Skill.Activation)
	require.Equal(t, "body content here\n", out[0].Skill.Body)
	require.Contains(t, out[0].Warnings, importedReplaceWarning)
	require.Equal(t, filepath.Join(root, ".junie", "guidelines", "alpha.md"), out[0].SourcePath)

	require.Equal(t, "beta", out[1].Skill.ID)
	require.Equal(t, "beta description", out[1].Skill.Description)
}

// TestImport_PerSkill_IgnoresNonIncludedFrontmatter ensures the include allow
// list filters out harness-only metadata that isn't part of the canonical
// surface.
func TestImport_PerSkill_IgnoresNonIncludedFrontmatter(t *testing.T) {
	a := loadFixtureAdapter(t, "import-per-skill")
	root := t.TempDir()
	writeFile(t, filepath.Join(root, ".junie", "guidelines", "gamma.md"),
		"---\ndesc: gamma description\nallowed-tools:\n  - Bash\nautoAttach: \"true\"\n---\n"+
			"> Auto-generated by adeptability. Do not edit by hand.\n\n"+
			"gamma body\n\n<!-- end -->")

	out, err := a.Import(context.Background(), root)
	require.NoError(t, err)
	require.Len(t, out, 1)
	// "allowed-tools" is not in the include list ([description, tags]); ignored.
	require.Empty(t, out[0].Skill.AllowedTools)
}

// TestImport_PerSkill_NoMatchesReturnsEmpty confirms a missing output
// directory is benign (no error, no skills) rather than a fatal condition.
func TestImport_PerSkill_NoMatchesReturnsEmpty(t *testing.T) {
	a := loadFixtureAdapter(t, "import-per-skill")
	out, err := a.Import(context.Background(), t.TempDir())
	require.NoError(t, err)
	require.Empty(t, out)
}

// TestImport_PerSkill_NoFrontmatter exercises the path where a file has no
// YAML header at all — we still recover the id from the filename and default
// activation/version.
func TestImport_PerSkill_NoFrontmatter(t *testing.T) {
	a := loadFixtureAdapter(t, "import-per-skill")
	root := t.TempDir()
	writeFile(t, filepath.Join(root, ".junie", "guidelines", "delta.md"),
		"> Auto-generated by adeptability. Do not edit by hand.\n\nfreeform body\n\n<!-- end -->")
	out, err := a.Import(context.Background(), root)
	require.NoError(t, err)
	require.Len(t, out, 1)
	require.Equal(t, "delta", out[0].Skill.ID)
	require.Equal(t, adept.ActivationAgent, out[0].Skill.Activation)
	require.NotEmpty(t, out[0].Skill.Description) // synthesized
	require.Equal(t, "freeform body\n", out[0].Skill.Body)
}

// TestImport_PerSkill_Sidecars verifies needs-directory adapters collect every
// non-SKILL.md file beside SKILL.md into Skill.Files.
func TestImport_PerSkill_Sidecars(t *testing.T) {
	a := loadFixtureAdapter(t, "import-per-skill-sidecars")
	root := t.TempDir()
	skillDir := filepath.Join(root, ".clone", "skills", "echo")
	writeFile(t, filepath.Join(skillDir, "SKILL.md"),
		"---\nsummary: echo a thing\nglobs:\n  - 'src/**/*.go'\n---\nmain body\n")
	writeFile(t, filepath.Join(skillDir, "scripts", "run.sh"), "#!/bin/sh\necho hi\n")
	writeFile(t, filepath.Join(skillDir, "references", "notes.md"), "see also\n")

	out, err := a.Import(context.Background(), root)
	require.NoError(t, err)
	require.Len(t, out, 1)
	require.Equal(t, "echo", out[0].Skill.ID)
	require.Equal(t, "echo a thing", out[0].Skill.Description)
	require.Equal(t, []string{"src/**/*.go"}, out[0].Skill.Globs)
	// Sidecars sorted by RelPath.
	require.Len(t, out[0].Files, 2)
	paths := []string{out[0].Files[0].RelPath, out[0].Files[1].RelPath}
	require.Equal(t, []string{"references/notes.md", "scripts/run.sh"}, paths)
	// No replace rules in this adapter — no warnings.
	require.Empty(t, out[0].Warnings)
}

// TestImport_AggregatorSingle_WithMarkers verifies split-by-marker for the
// single-file aggregator kind.
func TestImport_AggregatorSingle_WithMarkers(t *testing.T) {
	a := loadFixtureAdapter(t, "import-aggregator-single")
	root := t.TempDir()
	content := "<!-- adeptability:begin id=alpha hash=deadbeef -->\n" +
		"## alpha description\n" +
		"alpha body\n" +
		"<!-- adeptability:end id=alpha -->\n" +
		"<!-- adeptability:begin id=beta hash=cafebabe -->\n" +
		"## beta description\n" +
		"beta body\n" +
		"<!-- adeptability:end id=beta -->\n"
	writeFile(t, filepath.Join(root, "AGENTS.md"), content)

	out, err := a.Import(context.Background(), root)
	require.NoError(t, err)
	require.Len(t, out, 2)
	require.Equal(t, "alpha", out[0].Skill.ID)
	require.Equal(t, "alpha description", out[0].Skill.Description)
	require.Equal(t, "alpha body", out[0].Skill.Body)
	require.Equal(t, adept.ActivationAgent, out[0].Skill.Activation)
	require.Equal(t, "beta", out[1].Skill.ID)
}

// TestImport_AggregatorSingle_NoMarkers verifies the fallback path that
// synthesizes a single skill when the file has no markers.
func TestImport_AggregatorSingle_NoMarkers(t *testing.T) {
	a := loadFixtureAdapter(t, "import-aggregator-single")
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "AGENTS.md"), "freeform AGENTS content\n")
	out, err := a.Import(context.Background(), root)
	require.NoError(t, err)
	require.Len(t, out, 1)
	require.Equal(t, "agents", out[0].Skill.ID)
	require.Contains(t, out[0].Skill.Body, "freeform AGENTS content")
}

// TestImport_AggregatorSingle_MissingReturnsNil confirms the absence of the
// configured output is treated as an empty import rather than an error.
func TestImport_AggregatorSingle_MissingReturnsNil(t *testing.T) {
	a := loadFixtureAdapter(t, "import-aggregator-single")
	out, err := a.Import(context.Background(), t.TempDir())
	require.NoError(t, err)
	require.Empty(t, out)
}

// TestImport_AggregatorPerGlob_FrontmatterActivation exercises both the
// {glob}-templated walk and the applyTo-style frontmatter that supplies
// activation info to every skill in the bucket.
func TestImport_AggregatorPerGlob_FrontmatterActivation(t *testing.T) {
	a := loadFixtureAdapter(t, "import-aggregator-per-glob")
	root := t.TempDir()
	// Two bucket files; one explicit applyTo + markers, one no markers.
	writeFile(t, filepath.Join(root, ".github", "instructions", "src-ts.instructions.md"),
		"---\napplyTo: 'src/**/*.ts'\n---\n"+
			"<!-- adeptability:begin id=alpha hash=deadbeef -->\n"+
			"## alpha desc\nalpha body\n"+
			"<!-- adeptability:end id=alpha -->\n")
	writeFile(t, filepath.Join(root, ".github", "instructions", "default.instructions.md"),
		"---\napplyTo: '**'\n---\nfreeform default body\n")

	out, err := a.Import(context.Background(), root)
	require.NoError(t, err)
	// Sort defensively (adapter sorts, but we re-sort to be explicit).
	sort.Slice(out, func(i, j int) bool { return out[i].Skill.ID < out[j].Skill.ID })
	require.Len(t, out, 2)

	// alpha came from src-ts.instructions.md → globs activation.
	require.Equal(t, "alpha", out[0].Skill.ID)
	require.Equal(t, adept.ActivationGlobs, out[0].Skill.Activation)
	require.Equal(t, []string{"src/**/*.ts"}, out[0].Skill.Globs)

	// default has no markers → bucket-name fallback id; applyTo:** → always.
	require.Equal(t, "default", out[1].Skill.ID)
	require.Equal(t, adept.ActivationAlways, out[1].Skill.Activation)
}

// TestImport_AggregatorPerGlob_GlobsFrontmatterField verifies the alternate
// reverse-recovery key `globs:` is honored when the harness writes it instead
// of `applyTo:`.
func TestImport_AggregatorPerGlob_GlobsFrontmatterField(t *testing.T) {
	a := loadFixtureAdapter(t, "import-aggregator-per-glob")
	root := t.TempDir()
	writeFile(t, filepath.Join(root, ".github", "instructions", "ts.instructions.md"),
		"---\nglobs:\n  - 'src/**/*.ts'\n  - 'app/**/*.tsx'\n---\nfreeform body\n")
	out, err := a.Import(context.Background(), root)
	require.NoError(t, err)
	require.Len(t, out, 1)
	require.Equal(t, adept.ActivationGlobs, out[0].Skill.Activation)
	require.Equal(t, []string{"src/**/*.ts", "app/**/*.tsx"}, out[0].Skill.Globs)
}

// TestImport_RoundTrip_PerSkill confirms render → import is approximately
// idempotent for the per-skill case: the recovered Skill matches the inputs.
func TestImport_RoundTrip_PerSkill(t *testing.T) {
	a := loadFixtureAdapter(t, "import-per-skill-sidecars")
	root := t.TempDir()
	skill := &adept.Skill{
		ID:          "round",
		Description: "trip back",
		Activation:  adept.ActivationGlobs,
		Globs:       []string{"docs/**/*.md"},
		Body:        "core body content\n",
	}
	rendered, err := a.Renderer().Render(context.Background(), adept.RenderInput{
		Skill:   skill,
		Harness: a.Spec(),
		Project: adept.ProjectInfo{Name: "demo"},
	})
	require.NoError(t, err)
	// Write the rendered file to the fake project root.
	abs := filepath.Join(root, rendered.Path)
	require.NoError(t, os.MkdirAll(filepath.Dir(abs), 0o755))
	require.NoError(t, os.WriteFile(abs, rendered.Bytes, 0o644))

	out, err := a.Import(context.Background(), root)
	require.NoError(t, err)
	require.Len(t, out, 1)
	require.Equal(t, "round", out[0].Skill.ID)
	require.Equal(t, "trip back", out[0].Skill.Description)
	require.Equal(t, adept.ActivationGlobs, out[0].Skill.Activation)
	require.Equal(t, []string{"docs/**/*.md"}, out[0].Skill.Globs)
	require.Equal(t, "core body content\n", out[0].Skill.Body)
}

// TestImport_ImportRenameOverride exercises the explicit spec.Import.Rename
// hint. We build the synthetic adapter directly because the loader yaml has
// no need for the hint in normal use.
func TestImport_ImportRenameOverride(t *testing.T) {
	spec := Spec{
		ID:     "junie-override",
		Kind:   adept.KindPerSkill,
		Output: ".x/{id}.md",
		Frontmatter: Frontmatter{
			// Forward rename is non-bijective (two canonical keys both map
			// to "summary"); explicit reverse hint disambiguates.
			Rename: map[string]string{"description": "summary"},
		},
		Import: Import{
			Rename: map[string]string{"headline": "description"},
		},
	}
	a, err := NewSynthetic(spec)
	require.NoError(t, err)
	root := t.TempDir()
	writeFile(t, filepath.Join(root, ".x", "z.md"),
		"---\nheadline: explicit\n---\nbody\n")
	out, err := a.Import(context.Background(), root)
	require.NoError(t, err)
	require.Len(t, out, 1)
	require.Equal(t, "explicit", out[0].Skill.Description)
}

// TestImport_UnterminatedSectionMarkerFails ensures malformed aggregator
// content surfaces a clear error rather than silently truncating.
func TestImport_UnterminatedSectionMarkerFails(t *testing.T) {
	a := loadFixtureAdapter(t, "import-aggregator-single")
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "AGENTS.md"),
		"<!-- adeptability:begin id=alpha hash=deadbeef -->\n## alpha\nbody\n")
	_, err := a.Import(context.Background(), root)
	require.Error(t, err)
	require.True(t, strings.Contains(err.Error(), "unterminated"), err.Error())
}

// TestImport_UnterminatedFrontmatterFails verifies per-skill frontmatter that
// opens but never closes returns an error rather than yielding garbage.
func TestImport_UnterminatedFrontmatterFails(t *testing.T) {
	a := loadFixtureAdapter(t, "import-per-skill")
	root := t.TempDir()
	writeFile(t, filepath.Join(root, ".junie", "guidelines", "bad.md"),
		"---\ndesc: never closes\nbody continues\n")
	_, err := a.Import(context.Background(), root)
	require.Error(t, err)
}
